image: docker:latest
services: 
  - docker:dind

stages:
  - build
  - deploy

build-dev:
  image: vamarlier/awscli-on-docker-sbuild
  stage: build
  only:
    - "dev"
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t $DOCKER_REGISTRY/monitoring/orchestrator/dev:$CI_COMMIT_SHA .
    - docker tag $DOCKER_REGISTRY/monitoring/orchestrator/dev:$CI_COMMIT_SHA $DOCKER_REGISTRY/monitoring/orchestrator/dev
    - docker push $DOCKER_REGISTRY/monitoring/orchestrator/dev

build-prod:
  image: vamarlier/awscli-on-docker-sbuild
  stage: build
  only:
    - "master"
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t $DOCKER_REGISTRY/monitoring/orchestrator:$CI_COMMIT_SHA .
    - docker tag $DOCKER_REGISTRY/monitoring/orchestrator:$CI_COMMIT_SHA $DOCKER_REGISTRY/monitoring/orchestrator
    - docker push $DOCKER_REGISTRY/monitoring/orchestrator

deploy-dev:
  image: vamarlier/awscli-on-debian-sdeploy
  stage: deploy
  only:
    - "dev"
  script:
  ## prepare for scp and ssh
    - apt-get update
    - apt-get -yy install openssh-client sudo
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa $IP_TARGET_HOST >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/known_hosts
  ## login to remote docker registry
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "$(aws ecr get-login --no-include-email --region eu-west-1)"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker pull $DOCKER_REGISTRY/monitoring/orchestrator/dev"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker stop monitoring-orchestrator-dev && sudo docker rm monitoring-orchestrator-dev"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker run --name monitoring-orchestrator-dev -v /srv/orchestrator/conf-dev:/opt/orchestrator/configs -d --restart=unless-stopped $DOCKER_REGISTRY/monitoring/orchestrator/dev"


deploy-prod:
  image: vamarlier/awscli-on-debian-sdeploy
  stage: deploy
  only:
    - "master"
  script:
  ## prepare for scp and ssh
    - apt-get update
    - apt-get -yy install openssh-client sudo
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa $IP_TARGET_HOST >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/known_hosts
  ## login to remote docker registry
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "$(aws ecr get-login --no-include-email --region eu-west-1)"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker pull $DOCKER_REGISTRY/monitoring/orchestrator"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker stop monitoring-orchestrator-prod && sudo docker rm monitoring-orchestrator-prod"
    - sudo -u root ssh -i ~/.ssh/id_rsa dock@$IP_TARGET_HOST "docker run --name monitoring-orchestrator-prod -v /srv/orchestrator/conf-prod:/opt/orchestrator/configs -d --restart=unless-stopped $DOCKER_REGISTRY/monitoring/orchestrator"
  